language: php
php:
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=declare-tearDownAfterClass-void
    - APP_NAME=files_external_ftp
    - DB=sqlite
  matrix:
#    - FTPD=pure-ftpd
    - FTPD=proftpd
    - FTPD=vsftpd
    - FTPD=proftpd CORE_BRANCH=stable10
    - FTPD=vsftpd CORE_BRANCH=stable10

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq bc $FTPD
  - if [ "$FTPD" = "vsftpd" ]; then echo "local_enable=YES" | sudo tee -a /etc/vsftpd.conf; echo "write_enable=YES" | sudo tee -a /etc/vsftpd.conf; echo "pam_service_name=ftp" | sudo tee -a /etc/vsftpd.conf; mkdir -p /var/run/vsftpd/empty; fi
  - sudo service $FTPD restart

  - pass=$(perl -e 'print crypt("test", "password")')
  - sudo useradd -m -p $pass -s /bin/bash test

  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - pwd
  - ls -l
  - cd ../core
  - composer install
  - ./core_install.sh $DB
  - php occ app:enable files_external
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd ../core/apps/$APP_NAME
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - echo '{"host":"localhost","username":"test","password":"test"}' > config.json
  - pwd
  - ls -l
  - phpunit --version
  - phpunit --configuration phpunit.xml
  - ../../../lib/composer/bin/phpunit --version
  - ../../../lib/composer/bin/phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"

matrix:
  include:
    - php: 7.1
      env: FTPD=proftpd CORE_BRANCH=stable10
    - php: 7.1
      env: FTPD=vsftpd CORE_BRANCH=stable10
  fast_finish: true
